version: "3"
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: delivery
      PG_DATA: /var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: .
    volumes:
      - .:/delivery-center
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
