default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: docker
  password: docker
  database: delivery
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
